name: Build

on: [push]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Setup Nuget
    - name: Setup Nuget
      uses: nuget/setup-nuget@v1

    # Add MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    # Install the .NET5 workload
    - name: Install .NET5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    # Nuget Restore
    - name: Restore nuget packages
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    # Build .NET Framework 4.5
    - name: Build Hitokoto
      run: msbuild ${{env.SOLUTION_FILE_PATH}} -p:Configuration=${{env.BUILD_CONFIGURATION}} -p:Platform="Any CPU" -maxCpuCount

    # Build with .NET 5
    - name: Build Hitokoto.Core with .NET5
      run: dotnet build ./src/Hitokoto.Core/Hitokoto.Core.csproj --configuration ${{env.BUILD_CONFIGURATION}} --framework net5.0

    # Build with .NET Core 3.1
    - name: Build Hitokoto.Core with .NET Core 3.1
      run: dotnet build ./src/Hitokoto.Core/Hitokoto.Core.csproj --configuration ${{env.BUILD_CONFIGURATION}} --framework netcoreapp3.1

    # Build samples
    - name: Build Sample with .NET Core 3.1
      run: dotnet build ./samples/Hitokoto.Sample/Hitokoto.Sample.csproj --configuration ${{env.BUILD_CONFIGURATION}} --framework netcoreapp3.1

    - name: Build wpf Sample with .NET Core 3.1
      run: dotnet build ./samples/Hitokoto.Sample.wpf/Hitokoto.Sample.wpf.csproj --configuration ${{env.BUILD_CONFIGURATION}} --framework netcoreapp3.1
